## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [257]:
# your code
sluchajnij_masiv=np.random.random(size=10)+2.5
sluchajnij_masiv[(sluchajnij_masiv>3) & (sluchajnij_masiv<8)]*=-1
sluchajnij_masiv

array([ 2.69598286,  2.54522729,  2.82533033,  2.88867729,  2.77134903,
       -3.32873751,  2.85675333,  2.78093451, -3.04269608,  2.64092422])

**2.** Заменить максимальный элемент случайного массива на 0

In [297]:
# your code
sluchajnij_masiv[sluchajnij_masiv.max(axis=0)==sluchajnij_masiv]=0
print(sluchajnij_masiv)

[ 0.          0.          0.          0.          0.         -3.32873751
  0.          0.         -3.04269608  0.        ]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
# your code
rows=3
cols=3

array=np.arange(rows*cols).reshape(rows,cols)
mesh=np.meshgrid(*array)
np.stack([i.flatten() for i in mesh]).transpose()

array([[0, 3, 6],
       [0, 3, 7],
       [0, 3, 8],
       [1, 3, 6],
       [1, 3, 7],
       [1, 3, 8],
       [2, 3, 6],
       [2, 3, 7],
       [2, 3, 8],
       [0, 4, 6],
       [0, 4, 7],
       [0, 4, 8],
       [1, 4, 6],
       [1, 4, 7],
       [1, 4, 8],
       [2, 4, 6],
       [2, 4, 7],
       [2, 4, 8],
       [0, 5, 6],
       [0, 5, 7],
       [0, 5, 8],
       [1, 5, 6],
       [1, 5, 7],
       [1, 5, 8],
       [2, 5, 6],
       [2, 5, 7],
       [2, 5, 8]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
A=np.arange(24).reshape(8,3)
B=np.arange(4).reshape(2,2)
bin=np.isin(A,B)

arr=np.where(bin==True)[0] #take columns
np.unique(arr) #column numbers

array([0, 1])

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
rows=10
cols=3
arr=np.random.randint(low=0,high=2,size=rows*cols).reshape(rows,cols)
print(arr)
check=np.apply_along_axis(lambda x: len(np.unique(x)),1,arr)
print(np.array(check>1))
arr[np.array(check>1)]


[[0 1 0]
 [1 0 0]
 [1 1 0]
 [1 0 1]
 [0 0 1]
 [0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 1]
 [1 1 1]]
[ True  True  True  True  True False  True  True False False]


array([[0, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
rows=10
cols=3
arr=np.random.randint(low=0,high=2,size=rows*cols).reshape(rows,cols)
print(arr)
something=np.unique(arr, axis=0)
something

[[0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [1 1 0]
 [0 0 1]
 [0 1 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]]


array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [8]:
# your code
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
##############loop##############
result=1
for i in range(X.shape[0]*X.shape[1]):
    if i//X.shape[0]==i%X.shape[0] and X[[i//X.shape[0]],[i%X.shape[0]]]!=0:
        result*=X[[i//X.shape[0]],[i%X.shape[0]]]
    i+=1
print(result)
##############numpy##############
diagonal=X.diagonal()
print(int(np.prod(diagonal[diagonal!=0])))

[3]
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [24]:
# your code
x = np.array([1, 2, 2, 4]);y = np.array([4, 2, 1, 2])
##############loop##############
st=set()
result=True
for i in x:
    st.add(i)
for i in y:
    if i not in st:
        result=False
        break
print(result)
##############numpy##############
print(np.isin(x,y).all())


True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [27]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print((max(x)))
print(np.max(x))

7
7


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [33]:
# your code
x = np.array([2, 2, 2, 3, 3, 3, 5])
############usual python######
from collections import defaultdict
dict=defaultdict(int)
for i in x:
    dict[i]+=1
print(dict)
unique0=[]; counts0=[]
for a,b in dict.items():
    unique0.append(a)
    counts0.append(b)
print(unique0, counts0)
##############numpy#############
unique, counts=np.unique(x,return_counts=True)
print(unique, counts)


defaultdict(<class 'int'>, {np.int64(2): 3, np.int64(3): 3, np.int64(5): 1})
[np.int64(2), np.int64(3), np.int64(5)] [3, 3, 1]
[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [117]:
from scipy.spatial.distance import cdist
# your code
# Random seed for reproducibility
np.random.seed(42)

# X: 3 objects in 2-dimensional space
X = np.random.randint(0, 4,6).reshape(3,2)
print(X)
# Y: 4 objects in the same 2-dimensional space
Y = np.random.randint(0, 4,8).reshape(4,2)
print(Y)

print(np.sqrt(np.sum((X[:,None]-Y[None,:])**2,axis=2)))
dist = cdist(X, Y, metric="euclidean")
print(dist)



[[2 3]
 [0 2]
 [2 3]]
[[0 0]
 [2 1]
 [2 2]
 [2 2]]
[[3.60555128 2.         1.         1.        ]
 [2.         2.23606798 2.         2.        ]
 [3.60555128 2.         1.         1.        ]]
[[3.60555128 2.         1.         1.        ]
 [2.         2.23606798 2.         2.        ]
 [3.60555128 2.         1.         1.        ]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [178]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [179]:
# your code
average_calories=np.mean(calorie_stats)
average_calories

np.float64(106.88311688311688)

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
# your code
from copy import deepcopy #don't want to change initial data
calorie_stats_sorted=deepcopy(calorie_stats)
calorie_stats_sorted.sort(axis=0)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [181]:
# your code
median_calories=np.median(calorie_stats_sorted,axis=0)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
# your code

nth_percentile=np.percentile(calorie_stats_sorted,4)

70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [190]:
# your code
more_calories=calorie_stats_sorted[calorie_stats_sorted>60].__len__()*100/calorie_stats_sorted.__len__()
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [198]:
# your code
calorie_std=np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [193]:
# your code
print(f"""1) Average calories count in competitor companies is \
approximately {average_calories:.1f} which is 
{((1-60/average_calories)*100):.1f} % more than our serials have.""")
print(f"""2) Average calories cannot demonstrate\
this significant imbalance between our serials
and others since {((np.sum(calorie_stats[calorie_stats>average_calories])/np.sum(calorie_stats))*100):.1f} % \
of serials have more calories than an average count""")
print(f"""3) Most of serial calories count is distributed 
in range between {average_calories-calorie_std} and {average_calories+calorie_std}""")

1) Average calories count in competitor companies is approximately 106.9 which is 
43.9 % more than our serials have.
2) Average calories cannot demonstratethis significant imbalance between our serials
and others since 67.2 % of serials have more calories than an average count
3) Most of serial calories count is distributed 
in range between 87.52593154920862 and 126.24030221702515
